use_frameworks!

platform :ios, '9.0'

target 'CircularProgressView_Example' do
  pod 'CircularProgressView', :path => '../'

  target 'CircularProgressView_Tests' do
    inherit! :search_paths

    
  end
end
